name: FactionsPro
author: Tethered
version: 2.0.0-beta
main: FactionsPro\FactionMain
api: [3.0.0, 4.0.0]
softdepend: ["PureChat", "AntiSpamPro", "EssentialsPE", "EconomyAPI"]
permissions:
  f.command:
    description: ""
    default: true
